[project]
name = "masters-analysis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "pandas>=2.3.1",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
]
